### ISSUE TITLE
ARPAV Partners tab

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#11]
we suggest a possible order of the columns and new labels to provide more detailed instruction (it is a proposal, we can discuss them)

note: could we discuss about the possibility to merge the columns of external experts in one (e.g. default values for external expertise)?

![immagine](https://user-images.githubusercontent.com/98102967/153632652-e9d16680-5b70-48ed-92d1-5f8a1e73c996.png)

**Comment by natlio** [comment]
- We agree with the order/renaming of the columns. 
- It is not possible to assume a standard value for the personmonths of the external experts. Just to mention, however, that external experts include only office employees and therefore CF is calculated only for office related activities (e.g. energy use, material use/waste, transportation). For example, external experts for catering or for printing publication material etc should not be accounted. 
- In the Section "Partners", we propose that all cells should be blank (not filled in with the value 1) in order to avoid mistakes. The user may forget to fill in a cell so in this case an error could be shown to the user that a value is missing. The user should fill in the arithmetic cells with values equal or greater than zero.
