### ISSUE TITLE
ARPAV printable deliverables

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#13]
Is the calculation based on default values for average number of pages and paper size (as suggested by the methodology)? 
If yes, could the data entry be simplified accordingly , ascking only the number of copies?
If no (we retain all the columns) please check that the suggest default values are selected automatically for all the deliverable categories
Rollups are standard communication materials, aren't they? Should we account for or not?

**Comment by natlio** [comment]
- Yes we agree with that , we have already suggested (#8 ) that the columns "Average number of pages" and "Paper size" to be removed since default values are given.
- We could consider CF estimation from Rollups to be  similar with that of Posters. So ,if you agree,  the category "Poster" could be replaced with "Poster/Rollup"
