### ISSUE TITLE
Clarify the difference between initial and current

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#22]
you add the possibility to switch from "initial" to "current" modes in addition to "simple" and "advanced" modes. Sorry, but I don't remember the meaning of this additional feature; please, could you provide a clarification? Did you add a specific paragraph in our user manual about that, too?

**Comment by MaToSan24** [comment]
Simple and advanced modes refer to the preparation and execution phase respectively. Besides, the initial and current modes on each project refer to the status of the project on the starting (initial) moment and right now (currently). In that way, the user could be able to compare how has the project been modified since it was created, not needing to create a copy of the project for that purpose.

**Comment by natlio** [comment]
When I am trying to select "Current data" in the advanced use mode, the browser is rephresing all the time. Is this mode currently working?

**Comment by ARPAV2022** [comment]
We have to discuss how to deal with this new feature. It could be an helpful function for the user, but we have to pay attention to not increase the complexity of the overall picture.

In which phase of the project (preparation or execution?) the "current" status could be useful to the user?

If the goal is to compare values with the "initial" stauts, why should the user insert again all the data that he /she have already inserted in the initial status?

Why do you think it is better to report the current status instead of the initial status in the list of projects?

**Comment by natlio** [comment]
We think that the addition of the "initial" and "current" modes in the tool it is not necessary since there is already the possibility of creating a clone project where all the input data are already filled in without needing to insert again all the data. In this way , the tool will be less complex. 
We think that mainly in the simple use mode there is no need of calculating CF in two phases.
In the advanced use of the tool, this will be actually done for building scenarios. So, in the advanced use of the tool the user will have the choice to switch from e.g. "current status" to mitigation scenarios.
We can discuss this in the next meeting.

**Comment by ARPAV2022** [comment]
The labels have been changed, then I will suggest to close this specific issue.
