### ISSUE TITLE
"Clear" button not working?

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#23]
I have inserted values, for example, in the tab "Printable Deliverables" e.g. 
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/61784811/165741400-908e2d40-77cf-4059-ba22-527b5036dff0.png">

I then select the "Clear" button, but the values of copies remain. It seems that is not working. The same is for the input data of partners.

**Comment by MaToSan24** [comment]
The "Clear" button is meant to clear the content of the filter, which you can find between the "New printable deliverable" and "Save" buttons. It is not meant to clear the content of the whole table by deleting every item. We have replaced the "Clear" label with "Clear filters" in order to provide the user a more precise description of the button's behaviour.
