### ISSUE TITLE
Present VS past version of the tool

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#26]
[20220426_check_remedio_before_after.odt](https://github.com/isa-group/wecaremed/files/8602356/20220426_check_remedio_before_after.odt)

We are wondering if the difference of the values between the previous and the current version of the tool were expected from your side. You can find attached the difference for the REMEDIO project that is quite high.

Since this is a matter of methodology, I invite you to align with AUTH
Did you check the difference depends only on updated parameters and not to bugs and problems of the tool (internal robustness)?

Thank you

**Comment by ARPAV2022** [comment]
> [20220426_check_remedio_before_after.odt](https://github.com/isa-group/wecaremed/files/8602356/20220426_check_remedio_before_after.odt)
> 
> We are wondering if the difference of the values between the previous and the current version of the tool were expected from your side. You can find attached the difference for the REMEDIO project that is quite high.
> 
> Did you check the difference depends only on updated parameters and not to bugs and problems of the tool (internal robustness)?
> 
> Thank you

**Comment by ARPAV2022** [comment]
@natlio

**Comment by MaToSan24** [comment]
The calculations of the tool are fine since we checked them over and over. Some data that was being used for calculations like average fuel consumption, percentage distribution of travels, etc. were modified in the methodology, and so we updated the tool to match it (this update resulted in bigger CFs on average for the projects). Also, the REMEDIO project is missing the second page of partners that were included in the version prior to the update, as we have mentioned on issue #25 , so the CF in the current version of the tool should be even higher.

**Comment by natlio** [comment]
I attach an excel file where I made a comparison between the past and present versions of the tool. It includes CF for each emission source in tCO2/employee/year or tCO2/participant/event. You can find also some relative comments. 
Differences should exist only on the following sources: Fuels-Heat, Transportation, Events. 
Higher CF values are attributed mainly to the events section since in the updated tool a correction was made in the calculations related to travel. 
[old_Vs_new.xlsx](https://github.com/isa-group/wecaremed/files/8610495/old_Vs_new.xlsx)
edit: I updated the excel file

**Comment by ARPAV2022** [comment]
Thank you for your contribution.
The increase of the values in REMEDIO is (more or less) in the processes mentioned by @natlio (see sheet n.3 of the excel file).

An issue is maybe related to the printable deliverables because the value is 0; is it possible to add two digits after the comma so we can compare the value with the previous one?
[old_Vs_new.xlsx](https://github.com/isa-group/wecaremed/files/8638394/old_Vs_new.xlsx)

**Comment by MaToSan24** [comment]
> An issue is maybe related to the printable deliverables because the value is 0; is it possible to add two digits after the comma so we can compare the value with the previous one?

The actual value of the CF for printable deliverables is 0.0035812873850000004 t CO2e, and the values are rounded to 2 decimals, that is the reason why 0 is shown in the app.

**Comment by ARPAV2022** [comment]
Then I'm wondering why the value after the update is lower then the previous project, if the emissions factos (as far as I understood from @natlio ) are not changed for this  process.  Data input are remained the same.
Thank you for the clarification
