### ISSUE TITLE
Start/Finishing Date clarification

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#28]
I want to make a test for an one year project (i.e. 12 months). In case I use 05/2022 for starting date, which will be the month for the finishing date so as to have 12 months in total? How the tool is counting a whole month?

I am checking results for transportation which is dependent on the duration of the project.

**Comment by natlio** [comment]
It seems that 12 months correspond to Start: 05/2022 , end: 06/2023. Is this right? 

I was initially confused since the tool  enters by default as start/end month 05/2022 to 05/2024 and therefore I supposed that this corresponded to 2 years.

**Comment by MaToSan24** [comment]
The tool considers the first day of the month of the starting date and the last day of the month of the finishing date. For your project, if you select 05/2022 and 05/2023 the dates will actually be: 01/05/2022 - 31/05/2023, so that would be 1 year and 1 month. If you wanted an exact year, you would need to select 05/2022 and 04/2023 for the starting and finishing date respectively.

**Comment by ARPAV2022** [comment]
I would suggest to insert this kind of information in the guidelines of the tool or directly in the tool (? with a popo up or similar).

**Comment by MaToSan24** [comment]
This information has been added in the create/edit project view:
![image](https://user-images.githubusercontent.com/63660411/167398843-eb576d58-2e95-4f66-b290-4deae59a531c.png)
