### ISSUE TITLE
Simple use mode: Events and Equipment have not the "Save" button

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#38]
Is there a reason why those tabs have not the "Save" button?

**Comment by MaToSan24** [comment]
They are not actual tables, like every other section that has a "save" button, but a group of input boxes for numbers. We added that "save" buttons to the tables because some times, when an user updated their values, these changes were not saved correctly everytime.

We cannot modify the internal implementation of these tables and so, we cannot fix the problem of automatically updating correctly.

Thus, what we decided to do was to add a "save" button on every table in order to make sure that the changes would be saved correctly 100% of the times when clicked.

That being said, "Events" and "Equipment" sections in simple use mode don't need this button since they dont suffer from this faulty behaviour that the tables have.

**Comment by ARPAV2022** [comment]
Please, check the stability of "events" in simple mode because every time I log in the CF of the REMEDIO project is underestimated becasue all the data inserted in "Events" tab are deleted automatically.
![immagine](https://user-images.githubusercontent.com/98102967/172874413-ebc78b5e-0570-49d7-9b1f-2f4ffc7a8340.png)

This is a little bit annoying, becasue the changment has a relevant impact on CF. Notify me when everything is fixed and I can operate again inserting the data for the last time. Thank you Giacomo

**Comment by MaToSan24** [comment]
I've entered some test data in the "Current" mode, reloaded the page, logged out, logged in again and the data is still there. I don't know what could be happening to you in order for the data to be deleted.
![image](https://user-images.githubusercontent.com/63660411/173182471-27e2a1af-3f4c-44e7-a744-20afe78aa023.png)

Could you provide us more detailed info about the process you have followed?

**Comment by ARPAV2022** [comment]
Thank you,

but the issue was is in the "Initial" (now base) mode indeed. Have you tried also that?

**Comment by MaToSan24** [comment]
The implementation is that same for both "Initial" and "Current" modes. Even though, I have tried it again on the "Initial" mode and it works fine for me as well. Please, make sure to tell us whenever you face this problem again and sorry for the inconveniences you may have faced.

**Comment by ARPAV2022** [comment]
Thank you very muche; now it seems to work and retain data I have inserted. I can close the issue.
