### ISSUE TITLE
Advance use: events

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#42]
![immagine](https://user-images.githubusercontent.com/98102967/171414383-6d752091-cbc0-45fd-8e27-b5778b7d70e1.png)

It could be useful to allow also decimal digit in the column days (e.g. 1,5 days of meeting /event duration) >> see yellow line

It could be helful for the user to have a clear explanation that "online participants" and "duration (hour)" should be defined only in case of "mixed" or " "onlie" events. >> see red lines + If possibile it could be useful to hide those two columns in case of "in presence" meeting to decrease the complexity of the visualization (just a proposal, I don't know it is technically feasible).

**Comment by natlio** [comment]
We could accept to use decimal digit in the column days but in this case you have to consider that in the calculation of CF for hotel stay the duration of the stay (in days) will be the rounded number of the duration of the event in days.
We agree that the columns "on-line participants" and "hours per day" should be hidden in case of in-presence events, if possible.

**Comment by MaToSan24** [comment]
The fields that the user doesn't need to input has been hidden in order to show more clarity in the tool, I hope that helps.
![image](https://user-images.githubusercontent.com/63660411/171595466-b4f83748-aab8-4aad-9a0d-64e99b6e42b5.png)

Also, the possibility to insert decimal digits in the duration (days) column has been implemented.

**Comment by ARPAV2022** [comment]
OK thank you for your comments and improvement. Issue solved
