### ISSUE TITLE
Predefined cell for "new partner" line

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#50]
Is it possible to show a new partner line with predefined data equal to "0" (as it is for "Events")? 
Otherwise, you have to click in each cell even if the value is 0.

This is the line as it is now
![immagine](https://user-images.githubusercontent.com/98102967/173801903-9b76eb10-e2a8-4203-9410-6899969916d4.png)

The proposal is to show predefined digit equals to "0" in that line, as it is for "Events" (picture below)
![immagine](https://user-images.githubusercontent.com/98102967/173802260-8d0eae24-eeed-483c-b590-00ef0f0f555a.png)

**Comment by MaToSan24** [comment]
Originally, that was the behaviour of the tool, but we were asked to implement it the way it is currently. The goal of the current implementation is to prevent the user from calculating the CF of a project without actively have input data for partners, because if this is the case, and error is risen as you can see if you click on the calculate CF button when some partner is missing some data.

**Comment by ARPAV2022** [comment]
Ok it if fine for me, thank you; Clear instructions  reporting these alert will be crucial for the user. Thank you
