### ISSUE TITLE
Events and CF values are lost when you update a project

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#52]
If you have to modify some characteristics (name, call, duration) of a project in you list, you have to click UPDATE if you want to retain those infos; but in that case the events and the CF values are lost and you have to insert them again.

![immagine](https://user-images.githubusercontent.com/98102967/175915881-c7dd0481-582a-4863-9e12-625a0a65cc33.png)

Please, is it possibile to solve this issue?

**Comment by MaToSan24** [comment]
Again, we have checked this issue and the problem isn't showing up for us. As a proof of this, you can check the "UTC_copy_1 EDITED" project in the app. We have cloned the "UTC" project, renamed it, changed its date and the values are not missing. Are you sure that your issue does not have to do with values not saving in the project details view instead of a problem with project editing?

**Comment by ARPAV2022** [comment]
Finally, I hope this is the case. Thank you for the support.

**Comment by ARPAV2022** [comment]
I check again following these actions:
I cloned the project 20220506 test arpav - REMEDIO
I checked in the cloned project that all data have been correctly cloned
I clicked on "save project"
I renamed the cloned project as 20220506 test arpav - REMEDIO - deleted events
I clicked on updated project
I opened the cloned project (renamed) and the data of Events and CF are missing.

Thank you for your supprto

**Comment by MaToSan24** [comment]
We have followed your steps and you are right, but it seems that it only happens with the REMEDIO project specifically. It probably is because it was created a long time ago and the internal data schema has suffered many updates along the time, so it is probably lacking some kind of internal variable that is preventing it from functioning in the correct way. If you created a new project and input the data of remedio project into it, you would not lose the data anymore and you could clone it as much as you want, but in its current state, there is probably no solution, so consider transfering the data to a newly created project, please. (IMPORTANT: do not transfer the data by cloning the project, because it would transmit its faulty behaviour anyways, it must be a new project).

**Comment by ARPAV2022** [comment]
I created a new project called REMEDIO. 
I repeted the process of cloning, editing and updating to check, but the bug is stille there. Events and CF values are deleted when I edit and update the values (such as name or call number)

**Comment by LuisUsrDev** [comment]
This bug has been fixed, sorry for the inconvenience.
