### ISSUE TITLE
Error in the calculation of a new monitoring year

### ISSUE THREAD

**Issue by ARPAV2022** [isa-group/wecaremed#61]
Good morning,
I have created the project UTC_monitor_year3
I switch to monitoring phase in order to update new values in the tables (increasing some values in order to represent a project activity of 3 years)
I saved any tabs
I clicked on "recalculate" but the CF values do not change
![immagine](https://user-images.githubusercontent.com/98102967/177346629-b10a9978-729f-4f70-8a00-34eeec82b0b6.png)

and the popup says "All customs updated" while in other project the popup says "Project CF calculated"

**Comment by MaToSan24** [comment]
![image](https://user-images.githubusercontent.com/63660411/177367149-a415a3c6-96d1-4adb-8b4b-3b4a23ba7b9b.png)
The problem was that there wasn't any travel modes selected when departing from the hosting city in the Project participation in in-presence events tab. Having selectioned "airplane" for both, now it can calculate the CF correctly:
![image](https://user-images.githubusercontent.com/63660411/177367556-9cb92c42-af8a-4ba5-8d08-9879921cecfb.png)
![image](https://user-images.githubusercontent.com/63660411/177367517-bbaae155-700d-4eca-88b1-4b46a1d22e42.png)

**Comment by MaToSan24** [comment]
I will try to add some kind of warning for this case so the application will inform the user that the travel mode is missing, sorry for the inconvenience.
